### ISSUE TITLE
feat: Transfer sites to Linux 🦭

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman.com#337]
Per @mcdurdin 

> We have a bit of a priority on this now because PHP is ceasing to support Windows... We don't need to change PHP version, and I think nearly all the pages should be fine without changes. Primary things I can see are:
> * web.config -> .htaccess
> * Any places where we have backslashes in paths need to be forward slashes. Not likely to be many of these.
> * Consider downloadable file types, in case there are any issues there
>
>I don't think we have any executables in use on the site.
>Ubuntu version shouldn't be important, I hope -- just a reasonably recent one? It would be nice to be able to run them under Docker and/or Apache for Windows as well.

The sites that we need to transfer are:
- [x] https://help.keyman.com
- [ ] https://keyman.com
- [x] https://api.keyman.com (+ database)
- [x] https://keymanweb.com
- [x] https://s.keyman.com keymanapp/s.keyman.com#73
- [ ] Legacy sites:
  - [ ] https://blog.tavultesoft.com
  - [ ] https://keymankeyboards.com
  - [ ] https://r.keymanweb.com
  - [ ] https://tavultesoft.com

Reference
https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/php_support.md

Some [engineering documentation](https://docs.google.com/document/d/16hUSAO6zdKqHTiEqJXk-h3889a87CnmT6uJZwQ7FF1I/edit#) for @mcdurdin and @tim-eves

**Comment by darcywong00** [comment]
Jotting a list of TODO's for the keyman.com site:
* Apply permanent redirects
* keyboard redirects
* /.well-known/web.config

**Comment by mcdurdin** [comment]
IIS rewrite notes. Edit \windows\system32\inetsrv\config\applicationHost.config, add following section under `<system.webServer>` (edit `<rewrite>` if it already exists):

```xml
        <rewrite>
            <globalRules>
                <rule name="help.keyman-local.com forward proxy" stopProcessing="true">
                    <match url=".*" />
                    <conditions>
                        <add input="{HTTP_HOST}" pattern="^help\.keyman-local\.com|help\.keyman\.com\.local$" />
                    </conditions>
                    <action type="Rewrite" url="http://localhost:8055/{R:0}" />
                </rule>
                <rule name="s.keyman.com proxy" stopProcessing="true">
                    <match url=".*" />
                    <conditions>
                        <add input="{HTTP_HOST}" pattern="^s\.keyman-local\.com|s\.keyman\.com\.local$" />
                    </conditions>
                    <action type="Rewrite" url="http://localhost:8054/{R:0}" />
                </rule>
                <rule name="web.keyman-local.com proxy" stopProcessing="true">
                    <match url=".*" />
                    <conditions>
                        <add input="{HTTP_HOST}" pattern="^web\.keyman-local\.com|keymanweb\.com\.local$" />
                    </conditions>
                    <action type="Rewrite" url="http://localhost:8057/{R:0}" />
                </rule>
            </globalRules>
        </rewrite>
```

**Comment by mcdurdin** [comment]
Remaining work is listed in #403.
