### ISSUE TITLE
chore: Docker migration TODO 🦭

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#403]
Outstanding work that needs to be completed for the Docker-based/k8s-based website host transfer:

## help.keyman.com
- [x] http -> https upgrade on staging and production -- verify no needless .htaccess rules ➡ keymanapp/help.keyman.com#876
- [x] verify TIER on k8s ➡ keymanapp/help.keyman.com#877
- [x] staging: Use fleet to automatically deploy 
- [x] staging: Use pinned Docker images ➡keymanapp/help.keyman.com#890
- [x] remove legacy resources/kubectl folder (help.keyman.com repo) ➡ keymanapp/help.keyman.com#883
- [x] api/deploy
  - [x] rename api/deploy to _control/webhook/deploy (site-kubernetes-config repo) ➡ keymanapp/site-kubernetes-config#2
  - [x] serialized git pull -- preventing parallel git pulls/deploys
  - [x] don't forget post-pull tasks such as
    - [x] generating kbd index in init-container.sh
    - [x] CDN refresh in init-container.sh ➡ keymanapp/help.keyman.com#911
  - [x] update webhook endpoint on github
  - [x] Verify that rolling updates incl. timeouts etc is working well with keyman-staging
- [ ] production: Deploy
  - [x] Use fleet to automatically deploy (in site-kubernetes-config / rancher) @tim-eves 
  - [x] point production cluster to staging branch initially (in site-kubernetes-config) @tim-eves 
  - [x] Test locally @tim-eves 
  - [x] RAM limits @tim-eves 
  - [x] Turn off Azure deployment
  - [x] ensure *.keyman.com, keymanweb.com is in the CF origin cert loaded onto the production cluster
  - [x] Add production deploy webhook endpoint on github
  - [x] Merge staging -> master (in help.keyman.com repo)
  - [x] Swap production cluster to master branch (in site-kubernetes-config repo)
  - [x] Test locally
  - [x] webhook on github (production)
  - [x] Update DNS for help.keyman.com (on Cloudflare)
  - [ ] Remove from Azure

Post-Deployment:
- [ ] staging: for backend, use api-keyman-com.keyman to bypass Cloudflare
- [ ] production: for backend, use api-keyman-com.keyman to bypass Cloudflare

## keyman.com
- [x] /.well-known/web.config #404
  - [x] remove let's encrypt bits
  - [x] test remaining rules in .htaccess
- [x] verify TIER on k8s ➡ #405
- [x] http -> https upgrade on staging and production
- [x] _control/webhook/deploy 
  - [x] webhook on github (staging)
  - [x] test
- [x] staging: Use pinned Docker images ➡#406
- [x] k8s configuration
- [x] staging: Use fleet to automatically deploy 
- [x] production: Deploy (copy from help.keyman.com)

Post-Deployment:
- [ ] staging: for backend, use api-keyman-com.keyman to bypass Cloudflare
- [ ] production: for backend, use api-keyman-com.keyman to bypass Cloudflare

## api.keyman.com + database
- [x] Sort out TIER for k8s sites
- [x] verify TIER on k8s ➡ keymanapp/api.keyman.com#216
- [x] http -> https upgrade on staging and production
- [x] _control/webhook/deploy 
  - [x] webhook on github (staging)
  - [x] test
- [x] staging: Use pinned Docker images ➡ keymanapp/api.keyman.com#217, keymanapp/api.keyman.com#218
- [x] handle database rebuild requests for staging and production keymanapp/api.keyman.com#203
- [x] staging: verify that database is persisting over rebuilds and deployments
- [x] staging: bring up api.keyman-staging.com (DNS update on CloudFlare)
- [x] staging: Use fleet to automatically deploy keymanapp/api.keyman.com#205
- [x] production: Deploy (copy from help.keyman.com)
- [x] production: import statistics from existing Azure api db
- [x] production: verify that database is persisting over rebuilds and deployments
- [x] production: update "Notify api.keyman.com of updated keyboards" similar to staging
- [x] keymanapp/keyman#9843 blocks
 
Post-Deployment (if necessary?):
- [ ] staging: for backend, use api-keyman-com.keyman to bypass Cloudflare
- [ ] production: for backend, use api-keyman-com.keyman to bypass Cloudflare

## keymanweb.com
- [x] k8s configuration ➡ keymanapp/site-kubernetes-config#10, keymanapp/site-kubernetes-config#20
- [x] http -> https upgrade on staging and production
- [x] _control/webhook/deploy 
  - [x] webhook on github (staging)
  - [x] test
- [x] staging: Use fleet to automatically deploy 
- [x] staging: Use pinned Docker images ➡keymanapp/keymanweb.com#91
- [x] staging: bring up web.keyman-staging.com (DNS update on CloudFlare)
- [x] production: Deploy (copy from help.keyman.com)

Post-Deployment:
- [ ] staging: for backend, use api-keyman-com.keyman to bypass Cloudflare
- [ ] production: for backend, use api-keyman-com.keyman to bypass Cloudflare

## s.keyman.com
- [x] k8s configuration
- [x] Sort out TIER for k8s sites
- [x] verify TIER on k8s (_control/info.php as used on other sites)
- [x] http -> https upgrade on staging and production
- [x] _control/webhook/deploy 
  - [x] webhook on github (staging)
  - [x] test
- [x] staging: Use fleet to automatically deploy 
- [x] staging: Use pinned Docker images ➡keymanapp/s.keyman.com#154
- [x] staging: bring up s.keyman-staging.com (DNS update on CloudFlare)
- [x] production: Deploy (copy from help.keyman.com)

## shared-sites
- [x] merge v0.4, new tag, update all dep sites to use the tag
- [x] Refactor environment `getenv()` calls into module so we have a single global `KeymanSiteEnvironment` class

## reverse-proxy
- [x] Future: let users choose which sites they want to host locally, and munge internal links accordingly

## site-kubernetes-config
- [x] merge staging to main (and update rancher config accordingly), using /production and /staging folders in main ➡ https://github.com/keymanapp/site-kubernetes-config/pull/4

## General
- [x] Stop using keyman.com.local and keyman-local.com, and always use keyman.com.localhost
- [x] Update https://github.com/keymanapp/keyman/tree/master/docs/websites#how-to-set-up-a-local-web-server-for-the-keyman-web-pages ➡ keymanapp/keyman#10566
- [ ] Move legacy sites
  - [ ]  https://blog.tavultesoft.com/
  - [ ]  https://keymankeyboards.com/
  - [ ]  https://r.keymanweb.com/
  - [ ]  https://tavultesoft.com/

Note: legacy [Keyman Sites Migration](https://docs.google.com/document/d/16hUSAO6zdKqHTiEqJXk-h3889a87CnmT6uJZwQ7FF1I/edit) Google Doc

**Comment by darcywong00** [comment]
I'm making a separate bullet point for `/_control/ready.php` here rather than splicing into the big checklist at the top.
Based on Jan 22 discussions, we want each site to have a unique `/_control/ready` probe that k8s can test:

## /_control/ready probe ## 

- [ ] api.keyman.com
  *  test db connection, build status, as well as web server ready, and _common files, vendor files ready
  * .htaccess rewrite from /_control/ready to /_control/ready.php

- [ ] keymanweb.com
  *  test web server ready, and _common files, vendor files ready
  * .htaccess rewrite from /_control/ready to /_control/ready.php
- [ ] keyman.com
  *  test web server ready, and _common files, vendor files ready
  * .htaccess rewrite from /_control/ready to /_control/ready.php
- [ ] help.keyman.com
  *  test web server ready, and _common files, vendor files ready
  * .htaccess rewrite from /_control/ready to /_control/ready.php
   
- [ ] s.keyman.com
  *  plain text file (don't use _common)
  * .htaccess rewrite?

**Comment by darcywong00** [comment]
Making a separate bullet point for creating `production` branches off of `staging for each site.

- [ ] api.keyman.com
- [ ] keymanweb.com
- [ ] keyman.com
- [ ] help.keyman.com
- [ ] s.keyman.com
