### ISSUE TITLE
chore: prepare for deployment

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman.com#419]
- [x] update each of the B17S1 staging->master PRs with latest staging
  - [x] keymanapp/api.keyman.com#231
  - [x] keymanapp/help.keyman.com#992
  - [x] keymanapp/keyman.com#418
  - [x] keymanapp/keymanweb.com#102
  - [x] keymanapp/s.keyman.com#243
- [x] merge staging to master
  - [x] keymanapp/api.keyman.com#231
  - [x] keymanapp/help.keyman.com#992
  - [x] keymanapp/keyman.com#418
  - [x] keymanapp/keymanweb.com#102
  - [x] keymanapp/s.keyman.com#243
- [x] change over the site-kubernetes-config/production configuration to point to master branch instead of staging branch
    https://github.com/keymanapp/site-kubernetes-config/blob/d51a4b5153c9e0e8668c8d79aea212ba421608e1/production/base/kustomization.yaml#L8-L9
- [x] test deployment on each site (api db deploy seems fine) from git commit to branch
  - [x] test api
  - [x] test help
  - [x] test keyman.com
  - [x] test keymanweb.com
  - [x] test s.keyman.com
- [x] switch production tier to PRODUCTION
- [x] update keyman-staging.com to keyman.com TLS in production/ of site-kubernetes-config
- [x] switch over DNS
  - [x] api.keyman.com
  - [x] help.keyman.com
  - [x] keyman.com
  - [x] keymanweb.com
  - [x] s.keyman.com
- [ ] #426
- [x] cleanup out the ingress from staging
  - [x] https://github.com/keymanapp/site-kubernetes-config/blob/main/staging/api.keyman.com/patch/networking.yaml
  - [x] https://github.com/keymanapp/site-kubernetes-config/blob/main/staging/help.keyman.com/patch/networking.yaml
  - [x] https://github.com/keymanapp/site-kubernetes-config/blob/main/staging/keyman.com/patch/networking.yaml
  - [x] https://github.com/keymanapp/site-kubernetes-config/blob/main/staging/keymanweb.com/patch/networking.yaml
  - [x] https://github.com/keymanapp/site-kubernetes-config/blob/main/staging/s.keyman.com/patch/networking.yaml
- [x] reload statistics
- [x] enable production webhooks on PRODUCTION
- [x] production: update "Notify api.keyman.com of updated keyboards" similar to staging on build.palaso.org

**Comment by mcdurdin** [comment]
Moved the last administrative task to a new issue #426, @tim-eves, assigned to you.
